### ISSUE TITLE
WordPress 3.5 Compatibility

### ISSUE THREAD

**Issue by om4james** [OM4/cpt-editor#2]
Test the plugin to make sure its compatible with WordPress 3.5

Also, as per http://core.trac.wordpress.org/ticket/21948, WordPress 3.5 includes a new `post_type_labels_{$post_type}` filter.

Review this, and possibly update the CPT editor plugin to use that new filter, instead of the
`registered_post_type` hook that's currently being used.

**Comment by om4csaba** [comment]
Closing this issue because the functionality is working well without any modifications to the hooks.
